name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build node api server from api folder Dockerfile and push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          cd api
          docker build -t andeslam2019/k8s-test-node-api-server:latest .
          docker push andeslam2019/k8s-test-node-api-server:latest
          
      - name: Build node web app from web folder Dockerfile and push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          cd web
          docker build -t andeslam2019/k8s-test-node-web-app:latest .
          docker push andeslam2019/k8s-test-node-web-app:latest
      
#       - name: Build node web app from web folder Dockerfile and push
#         uses: docker/build-push-action@v2
#         with:
#           context: ./web/
#           push: true
#           tags: andeslam2019/k8s-test-node-web-app:latest
      
#       - name: Build node api server from api folder Dockerfile and push
#         uses: docker/build-push-action@v2
#         with:
#           context: ./api/
#           push: true
#           tags: andeslam2019/k8s-test-node-api-server:latest
